defmodule Arena.PhoenixTest do
  use ExUnit.Case, async: true

  alias Arena.Config

  # The facade's compiled-in "global" default server, started once for the module.
  setup_all do
    start_supervised!({Phoenix.PubSub, name: :phoenix_test_global_pubsub})
    :ok
  end

  defp config(name \\ :phoenix_test), do: Arena.Config.new(:"#{name}_#{System.unique_integer([:positive])}")

  describe "put_config/2 + arena_config/1" do
    test "put_config stashes the config on conn.private and arena_config reads it back" do
      cfg = config()
      conn = Arena.Phoenix.put_config(%{private: %{existing: :kept}}, cfg)

      assert conn.private.arena_config == cfg
      assert conn.private.existing == :kept
      assert Arena.Phoenix.arena_config(conn) == cfg
    end

    test "arena_config resolves from assigns (channel seam)" do
      cfg = config()
      assert Arena.Phoenix.arena_config(%{assigns: %{arena_config: cfg}}) == cfg
    end

    test "arena_config resolves from connect_info.private (LiveView connected mount)" do
      cfg = config()
      socket = %{private: %{connect_info: %{private: %{arena_config: cfg}}}}
      assert Arena.Phoenix.arena_config(socket) == cfg
    end

    test "arena_config is nil for production socket/conn shapes" do
      assert Arena.Phoenix.arena_config(%{assigns: %{}, private: %{}}) == nil
      assert Arena.Phoenix.arena_config(%{private: %{connect_info: %{session: %{}}}}) == nil
      assert Arena.Phoenix.arena_config(%{}) == nil
    end
  end

  describe "store_from_socket/1 + LiveView.on_mount/4" do
    test "stores the config AND runs its callbacks in the current process" do
      test_pid = self()

      cfg =
        config()
        |> Config.add_callback({__MODULE__, :ping_callback, [pid: test_pid]})

      socket = %{private: %{connect_info: %{private: %{arena_config: cfg}}}}

      # Run in a fresh process so the process dict starts empty.
      task =
        Task.async(fn ->
          assert Arena.Phoenix.store_from_socket(socket) == :ok
          {Config.current().owner, Process.get(:callback_ran)}
        end)

      assert {owner, true} = Task.await(task)
      assert owner == cfg.owner
      assert_receive {:callback_ran, ^cfg}
    end

    test "on_mount stores the config and returns {:cont, socket}" do
      cfg = config()
      socket = %{private: %{arena_config: cfg}}

      stored? =
        Task.async(fn ->
          assert {:cont, ^socket} = Arena.Phoenix.LiveView.on_mount(:default, %{}, %{}, socket)
          Config.current().owner == cfg.owner
        end)
        |> Task.await()

      assert stored?
    end

    test "on_mount is a no-op when no config is injected (prod)" do
      socket = %{private: %{connect_info: %{session: %{}}}}

      no_config? =
        Task.async(fn ->
          Arena.Phoenix.LiveView.on_mount(:default, %{}, %{}, socket)
          Config.current().owner == :arena_global
        end)
        |> Task.await()

      assert no_config?
    end
  end

  # callback used above: marks the current process and notifies the test
  @doc false
  def ping_callback(config, opts) do
    Process.put(:callback_ran, true)
    send(Keyword.fetch!(opts, :pid), {:callback_ran, config})
    :ok
  end

  describe "Arena.Phoenix.PubSub.server/1 resolution" do
    test "returns the :pubsub_name from the current process's config" do
      Config.new(:srv) |> Config.put(:pubsub_name, :PerTestServer) |> Config.store()
      assert Arena.Phoenix.PubSub.server(:GlobalDefault) == :PerTestServer
    end

    test "falls back to a $callers ancestor's :pubsub_name" do
      Config.new(:caller) |> Config.put(:pubsub_name, :CallerServer) |> Config.store()

      # A bare process with no config of its own, but the test pid in $callers:
      assert Task.async(fn -> Arena.Phoenix.PubSub.server(:GlobalDefault) end)
             |> Task.await() == :CallerServer
    end

    test "falls back to the default in production (no config anywhere)" do
      # Run in a fresh process with no $callers config to be unambiguous.
      assert spawn_and_get(fn -> Arena.Phoenix.PubSub.server(:GlobalDefault) end) == :GlobalDefault
    end
  end

  # A facade generated by the macro (server name is this throwaway atom).
  defmodule Facade do
    use Arena.Phoenix.PubSub, server: :phoenix_test_global_pubsub
  end

  describe "the generated facade (real Phoenix.PubSub)" do
    setup do
      per_test = :"phoenix_test_pertest_#{System.unique_integer([:positive])}"
      start_supervised!({Phoenix.PubSub, name: per_test})
      %{per_test: per_test}
    end

    test "routes to the per-test server when one is injected", %{per_test: per_test} do
      Config.new(:facade) |> Config.put(:pubsub_name, per_test) |> Config.store()

      Facade.subscribe("topic")
      Facade.broadcast("topic", :hello)
      assert_receive :hello

      assert Facade.server() == per_test
    end

    test "routes to the global default when nothing is injected" do
      assert Facade.server() == :phoenix_test_global_pubsub

      Facade.subscribe("topic")
      Facade.broadcast("topic", :global)
      assert_receive :global
    end
  end

  defp spawn_and_get(fun) do
    parent = self()
    # plain spawn → no $callers entry, so no ancestor config is found
    spawn(fn -> send(parent, {:result, fun.()}) end)
    receive do
      {:result, r} -> r
    after
      1000 -> flunk("no result")
    end
  end
end
